### ISSUE TITLE
Add default docstring to Enum class in aenum

### ISSUE THREAD

**Issue by havardthom** [ethanfurman/aenum#1]
Hi,
I'm using aenum with Pydantic models which generates an Openapi schema to use with Swagger UI. Pydantic will by default use the Enum class docstring as description in Swagger UI schema models.(https://github.com/samuelcolvin/pydantic/blob/13a5c7d676167b415080de5e6e6a74bea095b239/pydantic/schema.py#L620). 

In the regular enum library the default docstring "An enumeration" is set for the Enum class .(https://github.com/python/cpython/blob/ee9f98d9f4b881ee15868a836a2b99271df1bc0e/Lib/enum.py#L226)

Is it possible to add a similar default docstring for the Enum class in aenum? e.g. "An advanced enumeration".

Pydantic expects a docstring to be set for Enum class, without it an error string will show in the generated Swagger UI schema.

**Comment by ethanfurman** [comment]
Looks like I added it and forgot.  I went with 'An enumeration', though -- the Advanced part is in how they are created, not in how they act afterwards.
