### ISSUE TITLE
Convert test script to proper unittest test module

### ISSUE THREAD

**Issue by mcepl** [ethanfurman/aenum#12]
When packaging aenum for openSUSE I would like to switch from running the script directly to using our packaging macros which use `python3 -munittest` (and some environmental variables set up for our purposes), so I have created this [tempdir_missing.patch](https://github.com/ethanfurman/aenum/files/7071472/tempdir_missing.patch.txt), which moves 
all fixture settings from ``if __name__=="__main__":`` construct to proper `setUp` methods.

Unfortunately, apparently I have done something wrong because two test cases fail:
```
[   27s]
[   27s] ======================================================================
[   27s] ERROR: test_convert_ (aenum.test.TestIntEnumConvert)
[   27s] ----------------------------------------------------------------------
[   27s] Traceback (most recent call last):
[   27s]   File "/home/abuild/rpmbuild/BUILD/aenum-3.1.0/aenum/test.py", line 6247, in test_convert_
[   27s]     self.assertEqual(test_type.CONVERT_TEST_NAME_F,
[   27s]   File "/usr/lib64/python3.6/enum.py", line 326, in __getattr__
[   27s]     raise AttributeError(name) from None
[   27s] AttributeError: CONVERT_TEST_NAME_F
[   27s]
[   27s] ======================================================================
[   27s] ERROR: test_convert_value_lookup_priority (aenum.test.TestIntEnumConvert)
[   27s] ----------------------------------------------------------------------
[   27s] Traceback (most recent call last):
[   27s]   File "/home/abuild/rpmbuild/BUILD/aenum-3.1.0/aenum/test.py", line 6229, in test_convert_value_lookup_priority
[   27s]     self.assertEqual(test_type(5).name, 'CONVERT_TEST_NAME_A')
[   27s]   File "/home/abuild/rpmbuild/BUILD/aenum-3.1.0/aenum/__init__.py", line 2576, in __call__
[   27s]     return cls.__new__(cls, value)
[   27s]   File "/home/abuild/rpmbuild/BUILD/aenum-3.1.0/aenum/__init__.py", line 2927, in __new__
[   27s]     raise ve_exc
[   27s] ValueError: 5 is not a valid UnittestConvert
```

What do you think, please? Both about my patch (and the idea behind it) and what I do wrong.

[Complete build log](https://github.com/ethanfurman/aenum/files/7071476/_log.txt) with all packages used and all steps taken.

**Comment by ethanfurman** [comment]
I'm going to leave the test script as-is because that's how it works with my setup.

I did implement your changes to try and troubleshoot, and have one observation and one guess:
- test_v3.py should have a different name, or `unittest` will it include in separately (it runs once as an import, and again as a main)
-  perhaps that double-loading by unittest is what caused those global errors?
