### ISSUE TITLE
Regression - extend_enum broken for Flag and IntFlag as of version 3.0.0

### ISSUE THREAD

**Issue by perey** [ethanfurman/aenum#13]
`extend_enum` is broken for `Flag` and `IntFlag` under versions 3.0.0 and 3.1.0.

The following works in version 2.2.6:

    >>> class FlagTest(Flag): # Or IntFlag
    ...     NONE = 0
    ...     LOW = 1
    ...     MID = 2
    ...
    >>> extend_enum(FlagTest, 'HIGH', 4)
    >>> FlagTest.LOW | FlagTest.HIGH
    <FlagTest.HIGH|LOW: 5>
    >>> FlagTest(5)
    <FlagTest.HIGH|LOW: 5>

It fails under later versions, both when OR'ing two values together and when constructing from a value:

* `Flag` enums produce a `ValueError: FlagTest: invalid value: 5\n    given 0b0 101\n  allowed 0b0 011`
* `IntFlag` enums produce no error but return an `int`, not an enum

More detailed [test cases](https://github.com/ethanfurman/aenum/files/7238071/testcases.txt) attached, suitable for running with `doctest`:

    $ python -m doctest testcases.txt

**Comment by ethanfurman** [comment]
Thank you for the report, I'll look into it!

**Comment by ethanfurman** [comment]
This is fixed in 3.1.1.
