### ISSUE TITLE
AttributeError: referencing enum from a class function

### ISSUE THREAD

**Issue by BrendanSimon** [ethanfurman/aenum#16]
The following code fails with aenum (3.1.2)

The error is a class function can not reference the enumerated attributes.

This works with standard library `Enum` (both python 2.7 and 3.7).

````
AttributeError: E: no attribute 'AAA'
AttributeError: E: no attribute 'BBB'
````

```python
import aenum

class E(aenum.Enum):
    AAA=1
    BBB=4

    @property
    def is_aaa(self):
        return self == self.AAA

    def is_bbb(self):
        return self == self.BBB
```

````python
f = F.AAA

f.is_aaa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in is_aaa
  File "/home/brendan/.local/lib/python2.7/site-packages/aenum/__init__.py", line 272, in __get__
    '%s: no attribute %r' % (ownerclass.__name__, self.name)
AttributeError: E: no attribute 'AAA'

f.is_bbb()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 8, in is_bbb
  File "/home/brendan/.local/lib/python2.7/site-packages/aenum/__init__.py", line 272, in __get__
    '%s: no attribute %r' % (ownerclass.__name__, self.name)
AttributeError: E: no attribute 'BBB'
```

**Comment by ethanfurman** [comment]
A couple corrections:
- Python 2.7 doesn't have an `Enum` (you must be using a third-party library, possibly my `enum34`)
- `is_aaa` is not a class method

Thanks for the report, but this is expected behavior, and will also fail in 3.11+.

History:

In Python 3.4, when Enum was created, it was not possible to reference one member from another (so `F.AAA.BBB` failed, as did `self.AAA`).  In 3.5, due to a speed boost implementation detail, it became possible, but was strongly discouraged.

Future:

In Python 3.11 it is again possible to disallow member-to-member access, so that is what is happening.  Note that member-to-class-to-member access works fine:

```python
    @property
    def is_aaa(self):
        return self is self.__class__.AAA
```

On a stylistic note, the recommended way to test for an enum member is

```python
some_var = F.BBB
if some_var is F.AAA:
    # stuff
```

**Comment by BrendanSimon** [comment]
Thanks @ethanfurman 

Yes, enum34 on Python2.7, and yes I prefer to use aenum (as I am using `Flags` too).

Yes, it didn't feel right accessing other defined enum values via `self`, but that is allowable with standard classes.

Using `self.__class__.AAA` works, as does `E.AAA`.  Is one more efficient than the other?

I felt encapsulating the test in a method made the code more robust as I have the test in multiple places, so less chance of getting the test wrong somewhere (e.g. in a refactor).  If you had to test for multiple things then that probability increases.

e.g `if my_enum in [ X.CCC, X.AAA, X.FFF, X.EEE ] : # do stuff`

Having that test repeated in many places is more error prone.  One option is to set a module level variable with the list of things to check.

```python
CAFE = [ X.CCC, X.AAA, X.FFF, X.EEE ]

if my_enum in CAFE : # do stuff
```

Not sure what the python purists prefer, but I like the encapsulating in a function approach - but as always can be persuaded ;-)

Cheers :)

**Comment by ethanfurman** [comment]
`E.AAA` is only two lookups, while `self.__class__.AAA` is three.

If testing multiple things at once a function is fine.  I made the comment mainly because you were comparing with `==` instead of `is`

**Comment by BrendanSimon** [comment]
Yep.  Using `timeit` I can see that `is` performs much better than `==`.

Presumably it's a simple pointer comparison rather than a call to an equivalence function that does some checking.

Thanks :)
