### ISSUE TITLE
Why does `_generate_next_value_` method of `StrEnum` returns lower case?

### ISSUE THREAD

**Issue by function2-llx** [ethanfurman/aenum#17]
Hello, 

I notice that the `_generate_next_value_` method of `StrEnum` returns the lower case of its name by default. I found it a bit inconvenient when I use `auto` to generate the string representation while I also want it to be exactly the same as the name. On the other hand, if one wants lower case by default, there's already `LowerStrEnum`. So may I ask what's the point behind this, please?

Thanks in advance!

https://github.com/ethanfurman/aenum/blob/d80fba869ebe1eb99c9aedb174d158bf6dc42937/aenum/__init__.py#L3193-L3197

**Comment by ethanfurman** [comment]
There is also `UpperStrEnum`.  :-)

My experience with "magic strings" is that they are usually lower-case, while the recommendation for enum names is to be upper-case -- so I chose the default of lower-cased values to fit that usage.

If `UpperStrEnum` doesn't meet your needs, you can write your `_generate_next_value_` that does.
