### ISSUE TITLE
[BUG] RecursionError when using aenum along with with custom enum member access hook

### ISSUE THREAD

**Issue by johnaugustflynn** [ethanfurman/aenum#18]
I discovered this bug when using aenum along with pytorch-lightning 1.6, which caused a strange recursion error upon import. I've included below code to reproduce the issue and my root cause analysis.

### Code to Reproduce Issue
```python
from typing import Any
from enum import Enum, EnumMeta
import aenum


# metaclass copied directly from pytorch-lightning
class _OnAccessEnumMeta(EnumMeta):
    """Enum with a hook to run a function whenever a member is accessed.
    Adapted from:
    https://www.buzzphp.com/posts/how-do-i-detect-and-invoke-a-function-when-a-python-enum-member-is-accessed
    """

    def __getattribute__(cls, name: str) -> Any:
        obj = super().__getattribute__(name)
        if isinstance(obj, Enum):
            obj.deprecate()
        return obj

    def __getitem__(cls, name: str) -> Any:
        member: _OnAccessEnumMeta = super().__getitem__(name)
        member.deprecate()
        return member

    def __call__(cls, *args: Any, **kwargs: Any) -> Any:
        obj = super().__call__(*args, **kwargs)
        if isinstance(obj, Enum):
            obj.deprecate()
        return obj


class MyEnum(Enum, metaclass=_OnAccessEnumMeta):
    FOO = "bar"
```

### Cause of Error
With v1.6, pytorch-lightning added a hook to their enums to check for deprecated members, which adds an `isinstance()` call inside of `__getattribute__`: https://github.com/PyTorchLightning/pytorch-lightning/blob/663216fe3edaed12205066a5601f3449b6cc50b8/pytorch_lightning/utilities/enums.py#L46-L68

Meanwhile aenum overwrites the standard enum module's implementation of `__instancecheck__` to include code that calls `__getattribute__`: https://github.com/ethanfurman/aenum/blob/d80fba869ebe1eb99c9aedb174d158bf6dc42937/aenum/__init__.py#L3924-L3925

Therefore when accessing a member of a lightning enum, it calls `__getattribute__`, which if aenum has been imported, unexpectedly calls the aenum implementation of `__instancecheck__` rather than the standard one, which calls `__getattribute__`, which calls aenum's `__instancecheck__` again, etc., causing infinite recursion.

### Discussion
I was very surprised to see this package overwriting part of the standard library. I feel that is very dangerous as it can break other packages depending on it, as seen here. I'd really prefer an alternative implementation where the aenum `__instancecheck__` and  `__subclasscheck__` are only used on aenums rather than clobbering all enums used in a project.

**Comment by ethanfurman** [comment]
Thank you for the thorough report.

The two overrides are there as they are the only way to get `isinstance(aenum.enum, enum.Enum)` to be `True`.

Looking at fixes.

(Aside: the proper attribution is `https://stackoverflow.com/a/62309159/208880`.)

**Comment by ethanfurman** [comment]
There is a patch (https://github.com/PyTorchLightning/pytorch-lightning/pull/12750) ready to merged that will fix their `__getattribute__` implementation.

For `aenum`s part, there is now a much better error message in place when a recursion error is detected, along with a new function, `remove_stdlib_integration()`, to remove `__instancecheck__` and `__subclasscheck__` overrides from the stdlib `EnumType` -- this will prevent code attempting to verify that an aenum enum is an `Enum`, so this should be a temporary measure until the buggy `__getattribute__` can be fixed.

Mitigated in 3.1.9.

**Comment by johnaugustflynn** [comment]
Thanks so much for the patch! After installing 3.1.9 and running `python -c 'import aenum; import pytorchlightning'`  I no longer get an error. I only see 3.1.8 code though, can you please push the 3.1.9 code? I'd love to take a look at the changes. Thanks.

**Comment by ethanfurman** [comment]
Latest code pushed, and thanks for checking.  I wasn't expecting for it to work sync PyTorch-Lightning hasn't updated their code yet, so I reexamined my fix and realized that the check for `__subclasses__`, which I had removed, was the problem all along.  :-/

Glad it's fixed!
