### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by alucryd** [ethanfurman/aenum#25]
Hi there, could you please tag releases from now on, and at least the current one? I'm going to maintain this in the arch linux repositories and it would be very nice to have. Thanks in advance.

**Comment by ethanfurman** [comment]
I believe I am tagging them:

```
$ git tag -l
1.0
1.0.04
1.1.0
1.1.1
1.2.1
1.3.0
1.3.1
1.3.2
1.3.3
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.4.5
1.4.6
1.4.7
2.0.0
2.0.1
2.0.10
2.0.2
2.0.3
2.0.4
2.0.5
2.0.6
2.0.7
2.0.8
2.0.9
2.1.0
2.1.1
2.1.2
2.1.3
2.1.4
2.2.0
2.2.1
2.2.2
2.2.3
```

Am I missing something?

**Comment by alucryd** [comment]
You might not push them, I don't see them on github, and `git tag -l` doesn't show anything here.

Try `git push --tags`.

**Comment by ethanfurman** [comment]
Ah, that did it!  Tags should now show up.

**Comment by alucryd** [comment]
Thanks, they're only up to 2.2.3 though, could you at least tag 3.1.11? That way I can switch to tags from that version onwards.

**Comment by ethanfurman** [comment]
Fixed my creation scripts, more tags uploaded.

Thanks for the heads-up!

**Comment by alucryd** [comment]
Thanks!
