### ISSUE TITLE
[question] How would one make value comparisons between separate enums possible?

### ISSUE THREAD

**Issue by ItsCubeTime** [ethanfurman/aenum#26]
If I have 3 enums as such:
```py
from aenum import Enum

class QuadSidesEnum(Enum):
    TOP = "TOP"
    RIGHT = "RIGHT"
    BOTTOM = "BOTTOM"
    LEFT = "LEFT"

class QuadCornersEnum(Enum):
    TOPLEFT = "TOPLEFT"
    TOPRIGHT = "TOPRIGHT"
    BOTTOMLEFT = "BOTTOMLEFT"
    BOTTOMRIGHT = "BOTTOMRIGHT"

class QuadCorndersNSidesEnum(Enum):
    TOPLEFT = "TOPLEFT"
    TOPRIGHT = "TOPRIGHT"
    BOTTOMLEFT = "BOTTOMLEFT"
    BOTTOMRIGHT = "BOTTOMRIGHT"
    TOP = "TOP"
    RIGHT = "RIGHT"
    BOTTOM = "BOTTOM"
    LEFT = "LEFT"
```

When designing an API, how would one go about making value comparisons between my QuadCorndersNSidesEnum and QuadCornersEnum/QuadSidesEnum possible? Do I have any options beyond using `.value` directly in my expression, like `QuadCorndersNSidesEnum.TOPLEFT.value == QuadCornersEnum.TOPLEFT.value` ?

**Comment by ethanfurman** [comment]
The first question is why don't you have one enum with all eight values?

The easiest way to enable direct comparisons is to make them `StrEnum`s:

    class QuadSidesEnum(str, Enum):
        TOP = "TOP"
        # etc

The downside is that they are now directly comparable to `str`.

Slightly more work is adding an `__eq__` method to all three (or at least the last one):

        def __eq__(self, other):
            if isinstance(other, (QuadSidesEnum, QuadCornersEnum, QuadCornersNSidesEnum)):
                return self._value_ == other._value_
            else:
                return NotImplemented

---

If you can, please ask questions on Stackoverflow instead.  :-)
