### ISSUE TITLE
aenum 3.1.12 is on PyPi but not GitHub

### ISSUE THREAD

**Issue by brendan-simon-indt** [ethanfurman/aenum#28]
3.1.12 is on PyPi (released 30 Mar 2023) but I can't find out what has changed since 3.1.11 as the GitHub repository has no changelog or commits or tags for 3.1.12.

Are they hiding somewhere else?

Where should I be looking for the change details?

I installed a venv on a Linux (Debian 10 Buster) system.  The `CHANGES` file only goes up to `3.1.8`

```
$ pip list | grep aenum
aenum                3.1.12


$ head venv_3/lib/python3.7/site-packages/aenum/CHANGES
3.1.8
=====

recalculate bits used after all flags created (sometimes needed when a custom
`__new__` is in place.


3.1.7
=====
```

**Comment by alucryd** [comment]
@ethanfurman Please tag the newest release when you have the time, Arch Linux relies on tags and is stuck at 3.1.11 :/

**Comment by ethanfurman** [comment]
Updated git settings to automatically push tags from now on.  Thanks, @alucryd.

@brendan-simon-indt: github repo now up-to-date.

**Comment by alucryd** [comment]
Thank you!
