### ISSUE TITLE
AutoValue and MultiValue do not work each other

### ISSUE THREAD

**Issue by lkjell** [ethanfurman/aenum#3]
The new version of aenum breaks a lot.

Using `start` to set autoValue with MultiValue does not work. `values` attribute is missing elements from autoValue.

This does not work either:
https://github.com/ethanfurman/aenum/blob/master/aenum/doc/aenum.rst#start

Python 3.9

**Comment by ethanfurman** [comment]
Can you share an example of one your AutoValue/MultiValue enums?

**Comment by lkjell** [comment]
```
class Measurement(int, MultiValueEnum, start=0):
    one = "20110721"
    two = "20120911"
    three = "20110518"
```

Alternative using `class M(Enum, settings=(AutoValue, MultiValue), start=0)`
Does not give expected result.

**Comment by ethanfurman** [comment]
@lkjell  Haven't heard anything, I'll hope this is working!  Reopen if you still have issues.
