### ISSUE TITLE
Package is broken in 3.1.14 ModuleNotFoundError: No module named 'aenum._common'

### ISSUE THREAD

**Issue by jacksonliam** [ethanfurman/aenum#31]
aenum 3.1.12 works fine, the now automatically pulled pip dependency 3.1.14 is broken. 

```
  File "/home/liam/klippy-env/lib/python3.9/site-packages/aenum/__init__.py", line 7, in <module>
    from ._common import *
ModuleNotFoundError: No module named 'aenum._common'
```

Environment:
Raspberry Pi 3+, Raspbian Lite 32-bit (debian bullseye) Linux 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

**Comment by arkeet** [comment]
Indeed, aenum/__init__.py is much smaller and references some new modules that don't exist. Perhaps a work in progress mistakenly published to pypi?

**Comment by ethanfurman** [comment]
New package released -- does that one work properly?

**Comment by arkeet** [comment]
Yes, that one appears to work. Thanks!

**Comment by ethanfurman** [comment]
Hopefully I'll remeber to update the `MANIFEST.in` file next time I make such changes.  :-/
